$('buildCore').onclick=buildCore;
function parseIssueQty(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let t=N(v);if(!t||t==='-'||t==='--')return 0;let neg=false;if(t.startsWith('(')&&t.endsWith(')')){neg=true;t=t.slice(1,-1)}if(t.endsWith('-')){neg=true;t=t.slice(0,-1)}t=t.replace(/,/g,'').replace(/\s/g,'').replace(/[₹$€£]/g,'').replace(/[^0-9.+-]/g,'');let n=Number(t);if(!Number.isFinite(n))return 1;return neg?-Math.abs(n):n}
function buildCore(){let allowed=new Set(allowedLocations.map(NK)),filtered=plan.filter(r=>allowed.has(NK(r.Location))),g=new Map();filtered.forEach(r=>{let s=N(r['STO Number']);if(!s)return;if(!g.has(s))g.set(s,[]);g.get(s).push(r)});let blocked=new Set(bsto.map(N)),p=[];for(let [s,rows] of g){if(rows.length&&rows.every(r=>parseIssueQty(r['Issue Qty'])===0)&&!blocked.has(s))p.push(...rows)}let u=[...new Set(p.map(r=>N(r['STO Number'])))].filter(s=>s&&!mpending.map(N).includes(s));if(u.length)return unknownModal(u,p);continueCore(p)}
function unknownModal(u,p){$('mTitle').textContent='Pending / Block Decision';$('mBody').innerHTML='';u.forEach(s=>{let d=document.createElement('div');d.className='mrow';d.innerHTML=`<label>${s}</label><select data-sto="${s}"><option>Pending</option><option>Block</option></select>`;$('mBody').appendChild(d)});$('mSave').onclick=()=>{document.querySelectorAll('#mBody select').forEach(s=>{if(s.value==='Block'){if(!bsto.includes(s.dataset.sto))bsto.push(s.dataset.sto)}else if(!mpending.includes(s.dataset.sto))mpending.push(s.dataset.sto)});closeM();drawBsto();save();continueCore(p.filter(r=>!bsto.includes(N(r['STO Number']))))};openM()}
function continueCore(p){if(raipur.length)raipurModal(p);else finalCore(p,[])}
function raipurModal(p){$('mTitle').textContent='Raipur Setup';$('mBody').innerHTML='<div class="mrow"><label>Raipur SPlt</label><input id="rsplt" placeholder="Type SPlt"></div><div class="mrow"><label>Raipur Dispatch?</label><select id="rdisp"><option>Yes</option><option>No</option></select></div>';$('mSave').onclick=()=>{let s=N($('rsplt').value),d=$('rdisp').value,e=[];if(d==='No')e=raipur.map(r=>({SPlt:s,Plant:r.Plant,'Plant Name':'',Location:'Raipur','Material No.':r['Material No.'],Description:r.Description,'STO Qty':Q(r.Qty),'STO Number':''}));closeM();finalCore(p,e)};openM()}
function finalCore(p,e){core=p.map(r=>({SPlt:r.SPlt,Plant:r.Plant,'Plant Name':r['Plant Name'],Location:r.Location,'Material No.':r['Material No.'],Description:r.Description,'STO Qty':Q(r['STO Qty']),'STO Number':r['STO Number']})).concat(e);drawCore();$('coreInfo').textContent=`${core.length} rows • ${new Set(core.map(r=>N(r['STO Number'])).filter(Boolean)).size} STO`;refresh();toast('Core Pending ready')}
function drawCore(){drawPrev('coreTable',CC,core,limitValue('coreLimit'))}
$('coreLimit').onchange=drawCore;
$('sendPlan').onclick=()=>{if(!core.length)return toast('Pehle Core Pending build karein');let ss=[...new Set(core.map(r=>N(r.SPlt)).filter(Boolean))];$('mTitle').textContent='Send Data to Plan';$('mBody').innerHTML='';ss.forEach(s=>{let d=document.createElement('div');d.className='mrow';d.innerHTML=`<label>${s}</label><input data-splt="${s}" value="${spltPlanMap[s]||''}" placeholder="Plan Name or Ignore">`;$('mBody').appendChild(d)});$('mSave').onclick=()=>{let m=new Map();document.querySelectorAll('#mBody input').forEach(i=>{m.set(i.dataset.splt,N(i.value));spltPlanMap[i.dataset.splt]=N(i.value)});let a=new Map();core.forEach(r=>{let pn=m.get(N(r.SPlt));if(!pn||NK(pn)==='ignore')return;pn=canonicalRemark(pn);let k=RK(pn)+'||'+NK(r['Material No.'])+'||'+NK(r.Description);if(!a.has(k))a.set(k,{'Plan Name':pn,'Material No.':N(r['Material No.']),Description:N(r.Description),Qty:0});a.get(k).Qty+=Q(r['STO Qty'])});planning=[...a.values()];closeM();drawPlanning();refresh();save();toast(planning.length+' planning records')};openM()};
